version: '3.9'

services:
  db:
    container_name: movies-info-api-postgres
    hostname: db
    image: postgres:15.4
    env_file:
      - ./.env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'

  backend:
    container_name: movies-info-api-backend
    hostname: backend
    build:
      context: .
      dockerfile: configuration/Dockerfile
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=db
      - WAIT_HOSTS=db:${POSTGRES_PORT}
    ports:
      - '8080:8080'
    depends_on:
      - db
